# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
  aws-ecs: circleci/aws-ecs@1.2.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          requires:
            - build
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          tag: 'latest,${CIRCLE_TAG}'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: '${AWS_RESOURCE_NAME_PREFIX}-service'
          cluster-name: '${AWS_RESOURCE_NAME_PREFIX}-cluster'
          container-image-name-updates: 'container=${AWS_RESOURCE_NAME_PREFIX}-cluster,tag=${CIRCLE_TAG}'
jobs:
  build:
    docker:
      - image: circleci/node:12.14
    steps:
      - checkout
      - run: npm install
      - run: npm test
